# jingxiu
# r charpter1
y<- c(5,9,12,30,14,18,32,40)
mean(y)
var(y)
sd(y)
sort(y)
median(y)
summary(y)
fivenum(y)[c(2,4)]
fivenum(y)[4] - fivenum(y)[2]
diff(fivenum(y)[c(2,4)])
y2<- sort(y)[-length(y)]
y2
median(y2)
fivenum(y2)
diff(fivenum(y2)[c(2,4)])
hb <- c(141,148,132,138,154,142,150,146,155,158,150,140,147,148,144,150,149,145)
sort(hb)
length(hb)
summary(hb)
fivenum(hb)
range(hb)
diff(range(hb))
mean(hb)
sd(hb)
se<-sd(hb)/sqrt(length(hb))

par(mfrow=c(3,1))
stripchart(hb,main="Modern Englishman",xlab="head breadth(mm)")
stripchart(hb,method="stack",cex=2,main="larger points(cex=2),method is stack")
stripchart(hb,method="jitter",cex=2,frame.plot = FALSE,main="no frame,method is jitter")
library(ggplot2)
hb_df <- data.frame(hb)
p1 <- ggplot(hb_df,aes(x=hb))
p1 <- p1+geom_dotplot(binwidth=2)
p1 <- p1+labs(title="Modern Englishman head breadth")
p1 <- p1+xlab("head breadth(mm)")
p2 <- ggplot(hb_df,aes(x=hb))
p2 <- p2+geom_dotplot(binwidth=2,stackdir="center")
p2 <- p2+labs(title="Modern Englishman head breadth,stackdir=center")
p2 <- p2+xlab("head breadth(mm)") 
p3 <- ggplot(hb_df,aes(x=hb))
p3 <- p3+geom_dotplot(binwidth=2,stackdir="centerwhole")
p3 <- p3+labs(title="Modern Englishman head breadth,stackdir=centerwhole")
p3 <- p3+xlab("head breadth (mm)") 
library(gridExtra)
grid.arrange(p1,p2,p3,ncol=1)

par(mfrow=c(1,3))
hist(hb, main="Modern Englishman",xlab="head breadth (mm)")
hist(hb, breaks=15, main="Histogram, 15 breaks")
hist(hb, breaks=8, freq=FALSE, main="Histogram, density")
library(ggplot2)
hb_df<- data.frame(hb)
p <- ggplot(hb_df,aes(x=hb))
p <- p+geom_histogram(binwidth=5)
p <- p+labs(title="Modern Englishman head breadth")
print(p)

stem(hb)

stem(hb,scale=2)

stem(hb,scale=5)

fivenum(hb)
par(mfrow=c(1,1))
boxplot(hb,horizontal=TRUE,main="Modern Englishman", xlab="head breadth(mm)")
library(ggplot2)
hb_df <- data.frame(hb)
p <- ggplot(hb_df, aes(x="hb",y=hb))
p <- p + geom_boxplot()
p <- p + coord_flip()
p <- p + labs(title="Modern Englishman head breadth")
print(p)

par(mfrow=c(3,1))
hist(hb,freq=FALSE,main="Histogram with kernel density plot,Modern Englishman")
points(density(hb),type="1")
rug(hb)
library(vioplot)
vioplot(hb,horizontal=TRUE, col="gray")
title("Violin plot,Modern Englishman")
boxplot(hb,horizontal=TRUE,main="Boxplot, Modern Englishman",xlab="head breadth(mm)")
library(ggplot2)
